[workspace]

[package]
name = "host"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"
wasmtime = { version = "29.0.1", features = ["component-model"] }
wit-component = "0.224.0"
wasmtime-wasi = "29.0.1"
reqwest = { version = "0.12.12", features = ["blocking"] }
