[workspace]

[package]
name = "component"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
once_cell = "1.19.0"
regex = "1.10.3"
wit-bindgen = { version = "0.38.0", default-features = false, features = ["realloc", "macros"] }

[lib]
crate-type = ["cdylib"]
